### ISSUE TITLE
Unable to build opx-build docker image: The command '/bin/sh -c gpg --import...' returned a non-zero code: 2

### ISSUE THREAD

**Issue by sweatypolarbears** [open-switch/opx-build#64] opened 2018-12-03 10:42 UTC
I have been trying to create the opx-build docker image and using `./docker_build.sh` in the opx-build directory and have been getting the following error: `The command '/bin/sh -c gpg --import /usr/share/keyrings/debian-archive-keyring.gpg  && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key AD5073F1  && gpg --export AD5073F1 >/etc/apt/trusted.gpg.d/opx-archive-keyring.gpg' returned a non-zero code: 2`

My process is as follows:
```bash
somak@somak-HP-Pro-3330-MT:~/opx-build$ ./docker_build.sh

Sending build context to Docker daemon  161.8kB
Step 1/16 : FROM debian:stretch
  ---> 4879790bd60d
Step 2/16 : LABEL maintainer="ops-dev@lists.openswitch.net"
 ---> Using cache
 ---> bfa71a591678
Step 3/16 : ENV DIST stretch
 ---> Using cache
 ---> 6551b4380316
Step 4/16 : RUN apt-get -qq update && apt-get -qq upgrade -y  && apt-get -qq install -y --no-install-recommends     build-essential     cowbuilder     curl     debian-archive-keyring     debootstrap     dh-autoreconf     dh-systemd     fakechroot     fakeroot     git-buildpackage     gosu     lsb-release     python-apt     python-jinja2     python-lxml     python-pip     python-requests     sudo     vim     wget  && apt-get -qq autoremove -y && apt-get clean && rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 7dba8ea50531
Step 5/16 : RUN pip2 install pyang requests-file  && ln -s /usr/local/bin/pyang /usr/bin
 ---> Using cache
 ---> e7e557c6e6d4
Step 6/16 : RUN gpg --import /usr/share/keyrings/debian-archive-keyring.gpg  && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key AD5073F1  && gpg --export AD5073F1 >/etc/apt/trusted.gpg.d/opx-archive-keyring.gpg
 ---> Running in d295283d79a6
gpg: directory '/root/.gnupg' created
gpg: keybox '/root/.gnupg/pubring.kbx' created
gpg: cannot open '/dev/tty': No such device or address
The command '/bin/sh -c gpg --import /usr/share/keyrings/debian-archive-keyring.gpg  && gpg --keyserver hkp://keyserver.ubuntu.com:80 --recv-key AD5073F1  && gpg --export AD5073F1 >/etc/apt/trusted.gpg.d/opx-archive-keyring.gpg' returned a non-zero code: 2
```

This is the issue. I am completely new to both Openswitch and Docker. Could anyone explain to me what's wrong and how to remedy it?

**Comment by theucke** [comment] 2018-12-04 16:32
The `docker run` invocation in `docker_build.sh` does *not* include the `--tty` flag, but you'd think this would have been seen before. What version of Docker are you running? You can check with `docker version`. Additionally, what OS/OS version are you running?

I'll go and try to reproduce this, but in the meantime you can either use the prebuilt Docker image `opxhub/build:stretch` or modify [line 49 of `docker_build.sh`](https://github.com/open-switch/opx-build/blob/master/docker_build.sh#L49) to say `docker run --tty` instead of `docker run`.

**Comment by sweatypolarbears** [comment] 2018-12-05 07:42
> This has never been seen before. What version of Docker are you running? You can check with `docker version`. Additionally, what OS/OS version are you running?
> 
> I'll go and try to reproduce this, but in the meantime you can either use the prebuilt Docker image `opxhub/build:stretch` (just run `opx_run`) or try modifying the `gpg` commands in the [Dockerfile](https://github.com/open-switch/opx-build/blob/master/Dockerfile#L35) to say `gpg --no-tty ...` instead of `gpg...`.

Hi, I'm using Ubuntu 16.04 and my Docker version is 17.03.2 -ce on both server and client. I did try to modify the dockerfile to say `gpg --no-tty ... ` but I'm getting the same error. I'll try to use the prebuilt Docker image as you have suggested. Thanks!

**Comment by mwheatley2** [comment] 2019-01-11 21:47
Hi, did using the prebuilt Docker image work for you?

**Comment by sweatypolarbears** [comment] 2019-01-14 07:33
> Hi, did using the prebuilt Docker image work for you?

Hello, I tried using the prebuilt Docker image and proceeding but since I'm a beginner at Openswitch, I wasn't quite able to figure out how to use it. I did manage to fix the dockerfile to say "gpg --no-tty..." and build a Docker image of my own and get it running.

**Comment by mapatel7** [comment] 2019-02-06 00:24
In docker builds, there is an open issue with Debian that gpg goes into an interactive mode and hence passing --batch would fix the issue. It is better to use '--batch' than '--no-tty'. I have tested it and it works, i will create a pull request to change the Dockerfile.

Thanks,
Mithil

**Comment by mapatel7** [comment] 2019-02-11 19:28
The pull request has been merged and the issue is resolved.

**Closed by mapatel7** 2019-02-11 19:28 UTC
Labels: bug
